import numpy
import numpy.typing
import typing

class EnqueueMcapFileOptions:
    episode_uuid: str
    timestamp_ns: int
    topic: str
    def __init__(self, episode_uuid: str, topic: str, timestamp_ns: int) -> None: ...

class LogWriter:
    def __init__(self, *args, **kwargs) -> None: ...
    def enqueue_episode_data(self, payload: dict, timestamps: typing.Annotated[numpy.typing.ArrayLike, numpy.int64], options) -> None: ...
    def enqueue_session_data(self, session, options) -> None: ...
    def finalize_episode(self, episode_uuid: str) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...

class McapFileConfig:
    agent_id: str
    file_metadata_topic: str
    file_shard_size_limit_bytes: int
    output_dir: str
    def __init__(self, output_dir: str, filename_prefix: str, file_metadata_topic: str, agent_id: str, file_shard_size_limit_bytes: int) -> None: ...

class ThreadPoolLogWriterConfig:
    image_observation_keys: list[str]
    max_num_workers: int
    mcap_file_config: McapFileConfig
    def __init__(self, max_num_workers: int, image_observation_keys: list[str], mcap_file_config: McapFileConfig) -> None: ...

def create_log_writer(*args, **kwargs): ...
